{% set name = "autoviz" %}
{% set version = "0.0.84" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autoviz-{{ version }}.tar.gz
  sha256: db81eecd4c74206eba4bb1f9d89d3377b784453741fa33d30c9502ab6ce85aaa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ipython
    - jupyter
    - matplotlib-base
    - pandas
    - python >=3.6
    - scikit-learn
    - seaborn
    - statsmodels
    - xgboost

test:
  imports:
    - autoviz

about:
  home: https://github.com/AutoViML/AutoViz
  summary: Automatically Visualize any dataset, any size with a single line of code
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
