{% set name = "autoviz" %}
{% set version = "0.1.36" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autoviz-{{ version }}.tar.gz
  sha256: 5b854482dd5dca0e4bb02a4f81dd054afd7d328196a5863fc0a32c3a604aceed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bokeh ==2.4.2
    - emoji
    - fsspec ==0.8.3
    - holoviews ==1.14.6
    - hvplot ==0.7.3
    - ipython
    - jupyter
    - matplotlib-base >=3.3.3
    - nltk
    - pandas
    - panel ==0.12.6
    - python
    - scikit-learn
    - seaborn >=0.11.1
    - statsmodels
    - textblob
    - wordcloud
    - xgboost
    - xlrd

test:
  commands:
    - ipython -c "import autoviz"
    - pip list | grep -E "{{ name }}\s+{{ version }}"
  requires:
    - ipython
    - pip

about:
  home: https://github.com/AutoViML/AutoViz
  summary: Automatically Visualize any dataset, any size with a single line of code
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
