{% set name = "autoviz" %}
{% set version = "0.1.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autoviz-{{ version }}.tar.gz
  sha256: 2d0c5ed11bf51cfdc8883544f430d769cadf8e6e67d9e6d238f75b65d4ab6c86

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dask
    - datashader
    - hvplot
    - ipython
    - jupyter
    - matplotlib-base
    - pandas
    - python >=3.6
    - scikit-learn
    - seaborn
    - statsmodels
    - wordcloud
    - xgboost
    - xlrd

test:
  commands:
    - ipython -c "import autoviz"
  requires:
    - ipython

about:
  home: https://github.com/AutoViML/AutoViz
  summary: Automatically Visualize any dataset, any size with a single line of code
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
