{% set name = "autoviz" %}
{% set version = "0.1.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autoviz-{{ version }}.tar.gz
  sha256: 034b2fbeb0af6da29f889d5d467bb5646708a8ecb2e951ad5cdf6c110ae627ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dask
    - datashader
    - hvplot
    - ipython
    - jupyter
    - matplotlib-base
    - pandas
    - python >=3.6
    - scikit-learn
    - seaborn
    - statsmodels
    - wordcloud
    - xgboost
    - xlrd

test:
  commands:
    - ipython -c "import autoviz"
  requires:
    - ipython

about:
  home: https://github.com/AutoViML/AutoViz
  summary: Automatically Visualize any dataset, any size with a single line of code
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
